"""Extracts every number cited in paper/main.tex from its source report
JSON and writes paper/numbers.tex as \\newcommand macros. Nothing in
main.tex should be a hand-retyped number -- if a figure changes upstream,
rerun this and recompile; the discrepancy is impossible to introduce by
a copy-paste slip because there is no copy-paste step.

Usage: python paper/extract_numbers.py
"""

import glob
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

BASE = "/home/jay/gamma"


def latest(pattern):
    matches = sorted(glob.glob(pattern))
    if not matches:
        raise FileNotFoundError(pattern)
    return matches[-1]


def fnum(x, fmt="{:.3f}"):
    return fmt.format(x)


def main():
    macros = {}

    # --- P-A4-3: participation ratio range, both models ---
    for model, tag in [("mamba-130m", "OneThreeM"), ("mamba-370m", "ThreeSevenM")]:
        pca = json.load(open(latest(f"{BASE}/reports/phase1/state_corpus/{model}/state_corpus_pca__*.json")))
        prs = [row["participation_ratio_frac_of_ambient"] for row in pca["pca_per_layer"]]
        macros[f"ParticipationRatioMin{tag}"] = fnum(min(prs) * 100, "{:.3f}") + r"\%"
        macros[f"ParticipationRatioMax{tag}"] = fnum(max(prs) * 100, "{:.2f}") + r"\%"
        macros[f"NContexts{tag}"] = str(pca["n_contexts"])

    # --- P-A4-1: ordering test + P-A4-2 six-condition ---
    for model, tag in [("mamba-130m", "OneThreeM"), ("mamba-370m", "ThreeSevenM")]:
        six = json.load(open(latest(f"{BASE}/reports/phase1/transplant_five_condition/{model}/six_condition_combined__*.json")))
        for cond, label in [("same_context", "SameContext"), ("related_context", "Related"), ("unrelated_context", "Unrelated"),
                             ("on_manifold_noise", "OnManifold"), ("gaussian", "Gaussian"), ("permuted_real", "Permuted")]:
            macros[f"AucKl{label}{tag}"] = fnum(six["auc_kl_summary"][cond]["mean"], "{:.2f}")
        macros[f"OnManifoldMinusUnrelated{tag}"] = fnum(six["P_A4_2"]["on_manifold_minus_unrelated"]["mean"], "{:.2f}")
        macros[f"GaussianMinusOnManifold{tag}"] = fnum(six["P_A4_2"]["gaussian_minus_on_manifold"]["mean"], "{:.2f}")

    # --- relatedness regression + zero-intercept law ---
    for model, tag in [("mamba-130m", "OneThreeM"), ("mamba-370m", "ThreeSevenM")]:
        rel = json.load(open(latest(f"{BASE}/reports/phase1/relatedness_regression/{model}/relatedness_regression__*.json")))
        macros[f"PearsonR{tag}"] = fnum(rel["pearson_r"], "{:.3f}")
        macros[f"SpearmanR{tag}"] = fnum(rel["spearman_r"], "{:.3f}")

    # --- shape/content decomposition (computed inline, matches reports/phase1/convergent_synthesis.md) ---
    for model, tag in [("mamba-130m", "OneThreeM"), ("mamba-370m", "ThreeSevenM")]:
        six = json.load(open(latest(f"{BASE}/reports/phase1/transplant_five_condition/{model}/six_condition_combined__*.json")))
        raw = six["auc_kl_raw"]
        shape_gaps = [g - o for g, o in zip(raw["gaussian"], raw["on_manifold_noise"])]
        content_gaps = [o - u for o, u in zip(raw["on_manifold_noise"], raw["unrelated_context"])]
        s, c = sum(shape_gaps) / len(shape_gaps), sum(content_gaps) / len(content_gaps)
        macros[f"ShapeShare{tag}"] = fnum(100 * s / (s + c), "{:.1f}") + r"\%"

    # --- leverage regression null ---
    for model, tag in [("mamba-130m", "OneThreeM"), ("mamba-370m", "ThreeSevenM")]:
        lev = json.load(open(latest(f"{BASE}/reports/phase1/leverage_regression/{model}/leverage_regression__*.json")))
        macros[f"LeveragePearson{tag}"] = fnum(lev["pooled_pearson_r"], "{:.3f}")

    # --- P-A4-4 depth-localization (only if the full-scale run exists) ---
    for model, tag in [("mamba-130m", "OneThreeM"), ("mamba-370m", "ThreeSevenM")]:
        try:
            depth = json.load(open(latest(f"{BASE}/reports/phase1/state_legibility_depth_full/{model}/state_legibility_depth_full__*.json")))
            macros[f"NLayersAboveFloor{tag}"] = f"{depth['n_layers_ci_above_zero']}/{depth['num_layers']}"
            macros[f"DepthTrendTop1{tag}"] = fnum(depth["spearman_depth_top1diff_all_layers"], "{:.3f}")
            macros[f"PeakLayer{tag}"] = str(depth["peak_layer"])
        except FileNotFoundError:
            print(f"[extract_numbers] no full-scale state-legibility run yet for {model} -- skipping those macros")

    out_path = f"{BASE}/paper/numbers.tex"
    with open(out_path, "w") as f:
        f.write("% AUTO-GENERATED by paper/extract_numbers.py -- do not hand-edit.\n")
        f.write("% Every number here traces to a specific reports/**/*.json file; rerun\n")
        f.write("% the extraction script (not this file) if an upstream number changes.\n\n")
        for name, val in sorted(macros.items()):
            f.write(f"\\newcommand{{\\{name}}}{{{val}}}\n")

    print(f"wrote {out_path} ({len(macros)} macros)")


if __name__ == "__main__":
    main()
